import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useLocation, useNavigate } from 'react-router-dom';
import { FiShoppingBag, FiCheckCircle, FiXCircle, FiImage, FiChevronLeft, FiChevronRight } from 'react-icons/fi';
import { getLiveCatalog } from './AdminDashboard';
import { useCart } from '../context/CartContext';

export default function Shop() {
  const [catalog, setCatalog] = useState([]);
  const [selectedCategory, setSelectedCategory] = useState('All');
  const { addToCart } = useCart();
  const routerLocation = useLocation();
  const navigate = useNavigate();

  const [carouselIndices, setCarouselIndices] = useState({});
  const [highlightedId, setHighlightedId] = useState(null);

  // Normalized to perfectly match both Home Customizer and Admin slots natively
  const allowedCategories = ["Sarees", "Plain Cloth", "Shawls", "Dhoti Pancha"];

  // 1. Core database catalog fetch loop
  useEffect(() => {
    const syncDatabaseCatalog = async () => {
      const cloudCatalogData = await getLiveCatalog();
      setCatalog(cloudCatalogData);
    };
    syncDatabaseCatalog();
  }, []);

  // 2. IMMEDIATE INTERCEPTOR: Listens for incoming category redirection states instantly
  useEffect(() => {
    if (routerLocation.state?.autoFilterCategory) {
      const incomingCat = routerLocation.state.autoFilterCategory;
      // Normalizes alternative naming configurations safely if needed
      if (incomingCat === "Dhoti & Pancha") {
        setSelectedCategory("Dhoti Pancha");
      } else {
        setSelectedCategory(incomingCat);
      }
    }
  }, [routerLocation.state?.autoFilterCategory]);

  // 3. TARGET ITEM COORD TRACKER: Highlight and set correct visibility bounds once catalog populates
  useEffect(() => {
    if (routerLocation.state?.highlightProductId && catalog.length > 0) {
      const targetId = routerLocation.state.highlightProductId;
      setHighlightedId(targetId);

      const matchedItem = catalog.find(p => String(p.id) === String(targetId));
      if (matchedItem) {
        setSelectedCategory(matchedItem.category);
      }
    }
  }, [routerLocation.state?.highlightProductId, catalog]);

  // 4. Smooth scrolling viewport executor
  useEffect(() => {
    if (highlightedId && catalog.length > 0) {
      setTimeout(() => {
        const itemDomElement = document.getElementById(`product-node-${highlightedId}`);
        if (itemDomElement) {
          itemDomElement.scrollIntoView({ behavior: 'smooth', block: 'center' });
        }
      }, 300);
    }
  }, [highlightedId, selectedCategory, catalog]);

  const filteredProducts = selectedCategory === 'All'
    ? catalog
    : catalog.filter(p => p.category === selectedCategory);

  const handlePrevSlide = (e, id, totalImages) => {
    e.stopPropagation();
    const currentIdx = carouselIndices[id] || 0;
    setCarouselIndices({ ...carouselIndices, [id]: currentIdx === 0 ? totalImages - 1 : currentIdx - 1 });
  };

  const handleNextSlide = (e, id, totalImages) => {
    e.stopPropagation();
    const currentIdx = carouselIndices[id] || 0;
    setCarouselIndices({ ...carouselIndices, [id]: currentIdx === totalImages - 1 ? 0 : currentIdx + 1 });
  };

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="pt-24 md:pt-28 bg-tassar-cream min-h-screen pb-24 text-tassar-earth">
      <header className="max-w-6xl mx-auto px-4 sm:px-6 mb-6 md:mb-10 text-left border-b border-tassar-earth/30 pb-6">
        <span className="text-[10px] md:text-xs uppercase tracking-[0.2em] text-tassar-madderRed font-bold block">✦ DIRECT FROM THE LOOM</span>
        <h1 className="text-3xl md:text-4xl font-display font-bold mt-1 text-black">Artisan Marketplace</h1>
        <p className="text-xs md:text-base text-black font-normal mt-2 max-w-xl">Browse authentic creations generated by our local community weaving cluster hubs.</p>
      </header>

      {/* FILTER RIBBON BUTTONS - Smooth, non-blocking touch scrolls on mobile screens */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6 mb-6 md:mb-12">
        <div className="flex flex-row overflow-x-auto md:flex-wrap gap-2 border-b border-tassar-raw/40 pb-2 scrollbar-none [-webkit-overflow-scrolling:touch]">
          <button
            onClick={() => { setSelectedCategory('All'); setHighlightedId(null); }}
            className={`px-4 md:px-5 py-2 md:py-2.5 text-[10px] md:text-xs font-bold tracking-widest uppercase transition-all rounded-none shrink-0 ${selectedCategory === 'All' ? 'bg-tassar-earth text-tassar-cream font-black shadow-sm' : 'text-black hover:bg-white border border-transparent'}`}
          >
            All ({catalog.length})
          </button>
          {allowedCategories.map(cat => (
            <button
              key={cat}
              onClick={() => { setSelectedCategory(cat); setHighlightedId(null); }}
              className={`px-4 md:px-5 py-2 md:py-2.5 text-[10px] md:text-xs font-bold tracking-widest uppercase transition-all rounded-none shrink-0 ${selectedCategory === cat ? 'bg-tassar-earth text-tassar-cream font-black shadow-sm' : 'text-black hover:bg-white border border-transparent'}`}
            >
              {cat === "Dhoti Pancha" ? "Dhoti & Pancha" : cat} ({catalog.filter(p => p.category === cat).length})
            </button>
          ))}
        </div>
      </div>

      {/* COMPATIBLE MOBILE TWO COLUMN CARDS SYSTEM GRID */}
      <main className="max-w-6xl mx-auto px-2 sm:px-6">
        <AnimatePresence mode="wait">
          {filteredProducts.length === 0 ? (
            <motion.div key="empty-shop" className="bg-white border border-tassar-raw/40 p-12 md:p-16 text-center max-w-xl mx-auto">
              <FiShoppingBag className="text-2xl md:text-3xl text-tassar-raw mx-auto mb-4" />
              <h3 className="font-display text-base md:text-lg font-bold text-black mb-1">No Items Available</h3>
            </motion.div>
          ) : (
            <motion.div key="grid-active" className="grid grid-cols-2 lg:grid-cols-3 gap-3 sm:gap-6 md:gap-8">
              {filteredProducts.map((product) => {
                const currentSlide = carouselIndices[product.id] || 0;
                const imagesArray = product.images || [];
                const isTargetHighlighted = highlightedId === product.id;
                const checkInStock = product.in_stock === true;

                return (
                  <div
                    key={product.id}
                    id={`product-node-${product.id}`}
                    onClick={() => navigate(`/product/${product.id}`)}
                    className={`bg-white p-2.5 sm:p-4 shadow-sm flex flex-col justify-between relative group transition-all duration-500 border cursor-pointer hover:shadow-md ${
                      isTargetHighlighted
                        ? 'border-tassar-madderRed ring-2 ring-tassar-madderRed/20 scale-[1.01] shadow-xl'
                        : 'border-tassar-raw/40'
                    }`}
                  >
                    <div>
                      <div className="w-full aspect-[4/3] bg-tassar-cream border border-tassar-raw/20 relative overflow-hidden flex items-center justify-center mb-3">
                        {imagesArray.length > 0 ? (
                          <>
                            <img src={imagesArray[currentSlide]} className="w-full h-full object-contain" alt={product.name} />
                            {imagesArray.length > 1 && (
                              <>
                                <button onClick={(e) => handlePrevSlide(e, product.id, imagesArray.length)} className="absolute left-1 md:left-2 p-1 rounded-full bg-black/60 text-white opacity-0 group-hover:opacity-100 transition-opacity z-10 text-xs md:text-base"><FiChevronLeft /></button>
                                <button onClick={(e) => handleNextSlide(e, product.id, imagesArray.length)} className="absolute right-1 md:right-2 p-1 rounded-full bg-black/60 text-white opacity-0 group-hover:opacity-100 transition-opacity z-10 text-xs md:text-base"><FiChevronRight /></button>
                              </>
                            )}
                          </>
                        ) : (
                          <div className="flex flex-col items-center justify-center text-tassar-raw/60"><FiImage className="text-xl" /></div>
                        )}
                      </div>

                      <div className="flex flex-wrap gap-1 justify-between items-center mb-2">
                        <span className="text-[8px] md:text-[9px] font-bold uppercase tracking-wider bg-tassar-cream text-tassar-earth px-1.5 py-0.5 border border-tassar-raw/30 truncate max-w-[65px] md:max-w-none">
                          {product.category === "Dhoti Pancha" ? "Dhoti & Pancha" : product.category}
                        </span>
                        <span className={`text-[8px] md:text-[9px] font-bold tracking-wide uppercase flex items-center gap-0.5 md:gap-1 ${checkInStock ? 'text-emerald-700 font-black' : 'text-rose-700 font-black'}`}>
                          {checkInStock ? <><FiCheckCircle /> Active</> : <><FiXCircle /> Sold</>}
                        </span>
                      </div>

                      <div className="text-left space-y-1 mb-3">
                        <h3 className="font-display text-sm md:text-xl font-bold text-black tracking-wide truncate">{product.name}</h3>
                        <p className="text-[11px] md:text-sm text-neutral-600 font-normal line-clamp-2 leading-tight md:leading-normal">{product.description}</p>
                        <p className="font-mono text-sm md:text-lg font-black text-black pt-0.5">₹{Number(product.price).toLocaleString('en-IN')}</p>
                      </div>
                    </div>

                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        addToCart(product);
                      }}
                      disabled={!checkInStock}
                      className={`w-full py-2 md:py-3 text-[10px] md:text-xs font-bold tracking-widest uppercase transition-all ${checkInStock ? 'bg-tassar-earth text-tassar-cream hover:bg-tassar-madderRed' : 'bg-neutral-100 text-neutral-400 border border-neutral-200 cursor-not-allowed'}`}
                    >
                      {checkInStock ? "Add to Cart" : "Sold Out"}
                    </button>
                  </div>
                );
              })}
            </motion.div>
          )}
        </AnimatePresence>
      </main>
    </motion.div>
  );
}