import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useLocation } from 'react-router-dom'; // Hooks up path context detection
import { FiShoppingBag, FiCheckCircle, FiXCircle, FiImage, FiChevronLeft, FiChevronRight } from 'react-icons/fi';
import { getLiveCatalog } from './AdminDashboard';
import { useCart } from '../context/CartContext';

export default function Shop() {
  const [catalog, setCatalog] = useState([]);
  const [selectedCategory, setSelectedCategory] = useState('All');
  const { addToCart } = useCart();
  const routerLocation = useLocation(); // Catch passing redirection states

  const [carouselIndices, setCarouselIndices] = useState({});
  const [highlightedId, setHighlightedId] = useState(null);

  const allowedCategories = ["Sarees", "Plain Cloth", "Towels", "Dhupattas"];

  useEffect(() => {
    const syncDatabaseCatalog = async () => {
      const cloudCatalogData = await getLiveCatalog();
      setCatalog(cloudCatalogData);
    };
    syncDatabaseCatalog();
  }, []);

  useEffect(() => {
    if (routerLocation.state && catalog.length > 0) {
      const { autoFilterCategory, highlightProductId } = routerLocation.state;

      if (autoFilterCategory) {
        setSelectedCategory(autoFilterCategory);
      }

      if (highlightProductId) {
        setHighlightedId(highlightProductId);
        const matchedItem = catalog.find(p => p.id === highlightProductId);
        if (matchedItem) {
          setSelectedCategory(matchedItem.category);
        }
      }
    }
  }, [routerLocation, catalog]);

  // Automated scroll focus executor trigger loop
  useEffect(() => {
    if (highlightedId && catalog.length > 0) {
      setTimeout(() => {
        const itemDomElement = document.getElementById(`product-node-${highlightedId}`);
        if (itemDomElement) {
          itemDomElement.scrollIntoView({ behavior: 'smooth', block: 'center' });
        }
      }, 300);
    }
  }, [highlightedId, selectedCategory, catalog]);

  const filteredProducts = selectedCategory === 'All'
    ? catalog
    : catalog.filter(p => p.category === selectedCategory);

  const handlePrevSlide = (id, totalImages) => {
    const currentIdx = carouselIndices[id] || 0;
    setCarouselIndices({ ...carouselIndices, [id]: currentIdx === 0 ? totalImages - 1 : currentIdx - 1 });
  };

  const handleNextSlide = (id, totalImages) => {
    const currentIdx = carouselIndices[id] || 0;
    setCarouselIndices({ ...carouselIndices, [id]: currentIdx === totalImages - 1 ? 0 : currentIdx + 1 });
  };

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="pt-28 bg-tassar-cream min-h-screen pb-24 text-tassar-earth">
      <header className="max-w-6xl mx-auto px-6 mb-10 text-left border-b border-tassar-earth/30 pb-6">
        <span className="text-xs uppercase tracking-[0.2em] text-tassar-madderRed font-bold block">✦ DIRECT FROM THE LOOM</span>
        <h1 className="text-4xl font-display font-bold mt-1 text-black">Artisan Marketplace</h1>
        <p className="text-sm md:text-base text-black font-normal mt-2 max-w-xl">Browse authentic creations generated by our local community weaving cluster hubs.</p>
      </header>

      {/* FILTER RIBBON BUTTONS */}
      <div className="max-w-6xl mx-auto px-6 mb-12">
        <div className="flex flex-wrap gap-2 border-b border-tassar-raw/40 pb-2">
          <button onClick={() => { setSelectedCategory('All'); setHighlightedId(null); }} className={`px-5 py-2.5 text-xs font-bold tracking-widest uppercase transition-all rounded-none ${selectedCategory === 'All' ? 'bg-tassar-earth text-tassar-cream font-black shadow-sm' : 'text-black hover:bg-white border border-transparent'}`}>
            All Collections ({catalog.length})
          </button>
          {allowedCategories.map(cat => (
            <button key={cat} onClick={() => { setSelectedCategory(cat); setHighlightedId(null); }} className={`px-5 py-2.5 text-xs font-bold tracking-widest uppercase transition-all rounded-none ${selectedCategory === cat ? 'bg-tassar-earth text-tassar-cream font-black shadow-sm' : 'text-black hover:bg-white border border-transparent'}`}>
              {cat} ({catalog.filter(p => p.category === cat).length})
            </button>
          ))}
        </div>
      </div>

      {/* SHOP GRID MATRIX */}
      <main className="max-w-6xl mx-auto px-6">
        <AnimatePresence mode="wait">
          {filteredProducts.length === 0 ? (
            <motion.div key="empty-shop" className="bg-white border border-tassar-raw/40 p-16 text-center max-w-xl mx-auto">
              <FiShoppingBag className="text-3xl text-tassar-raw mx-auto mb-4" />
              <h3 className="font-display text-lg font-bold text-black mb-1">No Items Available</h3>
            </motion.div>
          ) : (
            <motion.div key="grid-active" className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-8">
              {filteredProducts.map((product) => {
                const currentSlide = carouselIndices[product.id] || 0;
                const imagesArray = product.images || [];
                const isTargetHighlighted = highlightedId === product.id;

                // FIX: Map database properties cleanly to stop stock layout crashes
                const checkInStock = product.in_stock === true;

                return (
                  <div
                    key={product.id}
                    id={`product-node-${product.id}`}
                    className={`bg-white p-4 shadow-sm flex flex-col justify-between relative group transition-all duration-500 border ${
                      isTargetHighlighted
                        ? 'border-tassar-madderRed ring-2 ring-tassar-madderRed/20 scale-[1.02] shadow-xl'
                        : 'border-tassar-raw/40'
                    }`}
                  >

                    {/* CAROUSEL CONTAINER SLIDER BOX */}
                    <div className="w-full aspect-[4/3] bg-tassar-cream border border-tassar-raw/20 relative overflow-hidden flex items-center justify-center mb-4">
                      {imagesArray.length > 0 ? (
                        <>
                          <img src={imagesArray[currentSlide]} className="w-full h-full object-cover" alt="" />
                          {imagesArray.length > 1 && (
                            <>
                              <button onClick={() => handlePrevSlide(product.id, imagesArray.length)} className="absolute left-2 p-1.5 rounded-full bg-black/60 text-white opacity-0 group-hover:opacity-100 transition-opacity z-10"><FiChevronLeft /></button>
                              <button onClick={() => handleNextSlide(product.id, imagesArray.length)} className="absolute right-2 p-1.5 rounded-full bg-black/60 text-white opacity-0 group-hover:opacity-100 transition-opacity z-10"><FiChevronRight /></button>
                            </>
                          )}
                        </>
                      ) : (
                        <div className="flex flex-col items-center justify-center text-tassar-raw/60"><FiImage className="text-2xl" /></div>
                      )}
                    </div>

                    <div className="flex justify-between items-center mb-2">
                      <span className="text-[9px] font-bold uppercase tracking-wider bg-tassar-cream text-tassar-earth px-2 py-0.5 border border-tassar-raw/30">{product.category}</span>
                      <span className={`text-[9px] font-bold tracking-wide uppercase flex items-center gap-1 ${checkInStock ? 'text-emerald-700 font-black' : 'text-rose-700 font-black'}`}>
                        {checkInStock ? <><FiCheckCircle /> Loom Active</> : <><FiXCircle /> Sold Out</>}
                      </span>
                    </div>

                    <div className="text-left space-y-1.5 mb-5">
                      <h3 className="font-display text-xl font-bold text-black tracking-wide">{product.name}</h3>
                      {/* FIX: Changed product.desc to product.description to display content text */}
                      <p className="text-xs md:text-sm text-black font-normal line-clamp-2">{product.description}</p>
                      <p className="font-mono text-lg font-black text-black pt-1">₹{Number(product.price).toLocaleString('en-IN')}</p>
                    </div>

                    <button
                      onClick={() => addToCart(product)}
                      disabled={!checkInStock}
                      className={`w-full py-3 text-xs font-bold tracking-widest uppercase transition-all ${checkInStock ? 'bg-tassar-earth text-tassar-cream hover:bg-tassar-madderRed' : 'bg-neutral-100 text-neutral-400 border border-neutral-200 cursor-not-allowed'}`}
                    >
                      {checkInStock ? "Add to Cart" : "Out of Stock"}
                    </button>
                  </div>
                );
              })}
            </motion.div>
          )}
        </AnimatePresence>
      </main>
    </motion.div>
  );
}